name:                discord-macrobot
version:             0.1.0.0
github:              "ofthegoats/discord-macrobot"
license:             BSD3
author:              "ofthegoats"
# todo provide valid email for maintainer
maintainer:          "47647338+ofthegoats@users.noreply.github.com"
copyright:           "2022 ofthegoats"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ofthegoats/discord-macrobot#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- emoji
- text
- unliftio
- containers

library:
  source-dirs: src

executables:
  discord-macrobot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-macrobot

tests:
  discord-macrobot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-macrobot
